name = "personal-starlight-site"
pages_build_output_dir = "./dist"
compatibility_date = "2025-04-02"
workers_dev = false

[build]
command = "pnpm build"

[vars]
NODE_VERSION = "v23"
PNPM_VERSION = "10"
