name = "personal-starlight-site"
pages_build_output_dir = "./dist"
compatibility_date = "latest"
compatibility_flags = [ "nodejs_compat_v2" ]

[vars]
NODE_VERSION = "v22"

[build]
command = "pnpm run build"
cwd = "build_cwd"
watch_dir = "build_watch_dir"