---
version: 2.1

orbs:
  megalinter: relativesure/megalinter@volatile

workflows:
  run-ml:
    jobs:
      - megalinter/run:
          persist_megalinter_reports: true
          run_git_operations: true
          flavor: javascript
          context:
            - Main Context
