version: '2.1'
orbs:
  megalinter: relativesure/megalinter@dev:alpha
workflows:
  run-megalinter:
    jobs:
      - megalinter/run:
          resource_class: relativesure/hetzner-ubuntu-kind
          flavor: javascript
          github_token: GH_PACKAGES_TOKEN

