version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
jobs:
  build:
    docker:
      - image: cimg/node:23.7.0
    parallelism: 10
    working_directory: ~/your-project
    steps:
      - checkout
      - browser-tools/install-chrome
      #- run: npm i -g pnpm
      - run: wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
      - run: source /home/circleci/.bashrc
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run: env && pnpm install -g @lhci/cli@0.14.0
      - run: pnpm run build
      - run: lhci autorun

workflows:
  run-lhci:
    jobs:
      - build:
          context:
            - Main Context
