version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  node: circleci/node@7.1.0

resource_class: relativesure/hetzner-ubuntu-kind

jobs:
  run-lhci:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/your-project
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: lhci autorun

workflows:
  run-lhci:
    jobs:
      - node/run:
          name: node-run
          pnpm-run: build
          override-ci-command: pnpm i
          pkg-manager: pnpm
      - run-lhci:
          context:
            - Main Context
          requires:
            - node-run