version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  node: circleci/node@7.1.0

resource_class: relativesure/hetzner-ubuntu-kind

jobs:
  run-lhci:
    executor: node/default
    working_directory: ~/your-project
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          override-ci-command: pnpm i
          pkg-manager: pnpm
      - run: pnpm run build
      - run: sudo pnpm install -g @lhci/cli@0.14.x
      - run: lhci autorun
  build:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/your-project
    steps:
      - checkout
      - browser-tools/install-chrome
      #- run: pnpm install
      #- run: pnpm run build
      - run: sudo pnpm install -g @lhci/cli@0.14.x
      - run: lhci autorun

workflows:
  run-lhci:
    jobs:
      - run-lhci:
          context:
            - Main Context