version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  node: circleci/node@7.1.0

resource_class: relativesure/hetzner-ubuntu-kind

jobs:
  run-lhci:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/your-project
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: lhci autorun

workflows:
  run-lhci:
    jobs:
      - node/install:
          name: build1
          install-pnpm: true
          node-version: 'latest'
      - node/install-packages:
          name: build2
          override-ci-command: pnpm i
          pkg-manager: pnpm
      - node/run:
          name: build3
          pnpm-run: build
      - run-lhci:
          context:
            - Main Context
          requires:
            - build1
            - build2
            - build3