version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
  node: circleci/node@7.1.0

resource_class: relativesure/hetzner-ubuntu-kind

jobs:
  prepare-lhci:
    executor: node/default
    working_directory: ~/your-project
    steps:
      - checkout
      - node/install:
          install-pnpm: true
          node-version: 'latest'
      - node/install-packages:
          override-ci-command: pnpm i
          pkg-manager: pnpm
      - node/install-packages:
          override-ci-command: pnpm install -g @lhci/cli@0.14.x
          pkg-manager: pnpm
      - node/install-packages:
          pnpm-run: build
          pkg-manager: pnpm
      - run: lhci autorun
  run-lhci:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/your-project
    steps:
      - browser-tools/install-chrome
      - run: lhci autorun

workflows:
  run-lhci:
    jobs:
      - prepare-lhci:
          context:
            - Main Context
      - run-lhci:
          context:
            - Main Context