version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
jobs:
  lighthouse:
    docker:
      - image: skybirddk/circleci-pnpm:latest
    working_directory: ~/your-project
    steps:
      - checkout
      - browser-tools/install-chrome
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run: pnpm run build
      - run: ./node_modules/.bin/lhci autorun

workflows:
  run-lhci:
    jobs:
      - lighthouse:
          context: Main Context
